In [2]:
import numpy as np
from sklearn import preprocessing

input_data = np.array([[-1.3, 3.9, 4.5],
[-5.3, -4.2, 3.3],
[-5.2, -6.5, -1.1],
[-5.2, 2.6, -2.2]])


ModuleNotFoundError: No module named 'sklearn'

Бінарізація

In [2]:
binarized_data = preprocessing.Binarizer(threshold=1.8).transform(input_data)
print("\n Binarized data:\n", binarized_data)


 Binarized data:
 [[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]]


Виключення середнього

In [3]:
print("\nBEFORE: ")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))



BEFORE: 
Mean = [-4.25  -1.05   1.125]
Std deviation = [1.7036725  4.40028408 2.83405628]

AFTER: 
Mean = [0.00000000e+00 5.55111512e-17 0.00000000e+00]
Std deviation = [1. 1. 1.]


Масштабування

In [4]:
data_scaled_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))

print("\nМin max scaled data:\n", data_scaled_minmax)
data_scaled_minmax.fit_transform(input_data)




Мin max scaled data:
 MinMaxScaler()


array([[1.        , 1.        , 1.        ],
       [0.        , 0.22115385, 0.82089552],
       [0.025     , 0.        , 0.1641791 ],
       [0.025     , 0.875     , 0.        ]])

Нормалізація

In [5]:
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nl1 normalized data:\n", data_normalized_l1)
print("\nl2 normalized data:\n", data_normalized_l2)



l1 normalized data:
 [[-0.13402062  0.40206186  0.46391753]
 [-0.4140625  -0.328125    0.2578125 ]
 [-0.40625    -0.5078125  -0.0859375 ]
 [-0.52        0.26       -0.22      ]]

l2 normalized data:
 [[-0.21328678  0.63986035  0.7383004 ]
 [-0.70435392 -0.55816726  0.43855999]
 [-0.61931099 -0.77413873 -0.13100809]
 [-0.83653629  0.41826814 -0.3539192 ]]
